-- Kazakh Learning App — MVP schema (spec: docs/superpowers/specs/2026-10-02-kazakh-app-mvp-design.md §6)

-- ───────────── Content (public read, no client writes) ─────────────

create table public.levels (
  code text primary key check (code in ('A1','A2','B1','B2','C1','C2')),
  sort int not null unique,
  is_available boolean not null default false,
  content_version int not null default 1
);

insert into public.levels(code, sort, is_available) values
  ('A1', 1, true), ('A2', 2, true),
  ('B1', 3, false), ('B2', 4, false), ('C1', 5, false), ('C2', 6, false);

create table public.topics (
  id bigint generated by default as identity primary key,
  level_code text not null references public.levels(code),
  slug text not null unique,
  sort int not null,
  icon text
);
create index topics_level_idx on public.topics(level_code, sort);

create table public.words (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.topics(id) on delete cascade,
  kk text not null,
  example_kk text not null check (length(trim(example_kk)) > 0),
  sort int not null
);
create index words_topic_idx on public.words(topic_id, sort);

create table public.translations (
  entity_type text not null check (entity_type in ('topic','word','example')),
  entity_id bigint not null,
  lang text not null check (lang in ('kk','ru','en','zh')),
  text text not null check (length(trim(text)) > 0),
  primary key (entity_type, entity_id, lang)
);

-- ───────────── User data (owner only) ─────────────

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  level_code text references public.levels(code),          -- null = onboarding not finished
  learning_lang text not null default 'ru' check (learning_lang in ('ru','en','zh')),
  ui_lang text not null default 'kk' check (ui_lang in ('kk','ru','en','zh')),
  streak int not null default 0 check (streak >= 0),
  last_active_date date,
  created_at timestamptz not null default now()
);

create table public.word_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id bigint not null references public.words(id) on delete cascade,
  box int not null default 0 check (box between 0 and 5),
  due_at timestamptz not null default now(),
  correct_count int not null default 0,
  wrong_count int not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, word_id)
);
create index word_progress_due_idx on public.word_progress(user_id, due_at);

create table public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);
create index chat_messages_user_idx on public.chat_messages(user_id, created_at);

create table public.content_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id bigint not null references public.words(id) on delete cascade,
  comment text not null check (length(comment) <= 1000),
  created_at timestamptz not null default now()
);

-- ───────────── Row Level Security ─────────────

alter table public.levels enable row level security;
alter table public.topics enable row level security;
alter table public.words enable row level security;
alter table public.translations enable row level security;
alter table public.profiles enable row level security;
alter table public.word_progress enable row level security;
alter table public.chat_messages enable row level security;
alter table public.content_reports enable row level security;

create policy "content readable" on public.levels for select using (true);
create policy "content readable" on public.topics for select using (true);
create policy "content readable" on public.words for select using (true);
create policy "content readable" on public.translations for select using (true);

create policy "own profile read" on public.profiles for select using (user_id = auth.uid());
create policy "own profile update" on public.profiles for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "own progress" on public.word_progress for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "own chat read" on public.chat_messages for select using (user_id = auth.uid());
-- chat rows are written only by the tutor Edge Function (service role)

create policy "report insert" on public.content_reports for insert
  with check (user_id = auth.uid());

grant usage on schema public to anon, authenticated;
grant select on public.levels, public.topics, public.words, public.translations to anon, authenticated;
grant select, update (display_name, level_code, learning_lang, ui_lang) on public.profiles to authenticated;
grant select, insert, update on public.word_progress to authenticated;
grant select on public.chat_messages to authenticated;
grant insert on public.content_reports to authenticated;
grant usage on sequence public.content_reports_id_seq to authenticated;

-- ───────────── Profile on sign-up ─────────────

create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles(user_id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'), ''), split_part(new.email, '@', 1))
  );
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ───────────── RPC: streak (spec §5.2) ─────────────

create function public.record_activity(p_local_date date)
returns table(streak int, last_active_date date)
language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'not signed in' using errcode = 'insufficient_privilege';
  end if;

  return query
  update public.profiles p set
    streak = case
      when p.last_active_date is null or p_local_date > p.last_active_date + 1 then 1
      when p_local_date = p.last_active_date + 1 then p.streak + 1
      else p.streak                                   -- same day or earlier (clock skew)
    end,
    last_active_date = greatest(coalesce(p.last_active_date, p_local_date), p_local_date)
  where p.user_id = uid
  returning p.streak, p.last_active_date;
end $$;

-- ───────────── RPC: save one answer (spec §5.1) ─────────────

create function public.upsert_progress(p_word_id bigint, p_box int, p_due_at timestamptz, p_correct boolean)
returns void
language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'not signed in' using errcode = 'insufficient_privilege';
  end if;
  if p_box < 0 or p_box > 5 then
    raise exception 'box out of range' using errcode = 'check_violation';
  end if;

  insert into public.word_progress as wp (user_id, word_id, box, due_at, correct_count, wrong_count, updated_at)
  values (uid, p_word_id, p_box, p_due_at, case when p_correct then 1 else 0 end, case when p_correct then 0 else 1 end, now())
  on conflict (user_id, word_id) do update set
    box = excluded.box,
    due_at = excluded.due_at,
    correct_count = wp.correct_count + excluded.correct_count,
    wrong_count = wp.wrong_count + excluded.wrong_count,
    updated_at = now();
end $$;

revoke execute on function public.record_activity(date) from public, anon;
revoke execute on function public.upsert_progress(bigint, int, timestamptz, boolean) from public, anon;
grant execute on function public.record_activity(date) to authenticated;
grant execute on function public.upsert_progress(bigint, int, timestamptz, boolean) to authenticated;
